Try again

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -27,7 +27,6 @@ jobs:
         run: python scripts/install-serverless-plugins.py
       - name: Serverless deploy
         id: sls_deploy
-        continue-on-error: true
         env:
           SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
           DOMAIN_CERTIFICATE_ARN: ${{ secrets.DOMAIN_CERT_ARN }}
@@ -36,7 +35,7 @@ jobs:
           SNS_ANDROID_PLATFORM_APPLICATION_ARN: ${{ secrets.SNS_ANDROID_PLATFORM_APPLICATION_ARN }}
         run: |
           set -x
-          output=$(npx serverless deploy \
+          npx serverless deploy \
             --param "recipeTTL=${{ vars.RECIPE_TTL }}" \
             --param "recipeReadyNotificationBody=${{ vars.RECIPE_READY_NOTIFICATION_BODY }}" \
             --param "recipeReadyNotificationTitle=${{ vars.RECIPE_READY_NOTIFICATION_TITLE }}" \
@@ -45,10 +44,4 @@ jobs:
             --param "promptIdEN=${{ vars.AI_PARSING_PROMPT_ID_EN }}" \
             --param "maxAiParseRetryCount=${{ vars.MAX_AI_PARSE_RETRY_COUNT }}" \
             --param "domainName=${{ vars.DOMAIN_NAME }}" \
-            --param "aiModelName=${{ vars.AI_MODEL_NAME }}")
-          set +x
-          echo "command-output=$output" >> $GITHUB_OUTPUT
-
-      - name: Swallow bogus serverless error
-        run: |
-          echo "${{ steps.sls_deploy.outputs.command-output }}" | grep -qsv "ServerlessError2: Could not resolve provider.httpApi.id parameter. Expected params.ApiId to be a string"
+            --param "aiModelName=${{ vars.AI_MODEL_NAME }}" | tee --output-error warn /dev/null | grep -qs "ServerlessError2: Could not resolve provider.httpApi.id parameter. Expected params.ApiId to be a string" && false || true
